### ISSUE TITLE
Artefacts is mispelt in a few places -> Artifacts

### ISSUE THREAD

**Issue by cer** [microservices-patterns/ftgo-consumer-web-ui#7]
https://github.com/microservices-patterns/ftgo-consumer-web-ui/blob/bf614ad631bbe499cf329ed15f2701457305491d/.circleci/config.yml#L17

**Comment by dartandrevinsky** [comment]
I realized I made the typo and corrected it independently of this issue. Still linking it here: https://github.com/microservices-patterns/ftgo-consumer-web-ui/commit/29cf0a095141e5ddbc00a2f69090f24788180493

**Comment by dartandrevinsky** [comment]
Corrected:

![image](https://user-images.githubusercontent.com/9859370/115782311-3307d180-a3c4-11eb-8631-e02d420aba51.png)

![image](https://user-images.githubusercontent.com/9859370/115782326-39964900-a3c4-11eb-9fd4-cf3be5e51fcf.png)
